# Generated by Django 3.2.23 on 2024-01-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='greeting',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
