# Generated by Django 3.2.23 on 2024-01-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0002_alter_wall_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='profile',
        ),
    ]
