# Generated by Django 3.2.23 on 2024-01-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('landscapes', 'landscapes'), ('animals', 'animals'), ('plants', 'plants'), ('abstraction', 'abstraction'), ('other', 'other')], default='other', max_length=32),
        ),
    ]
